[package]
name = "ena_rs"
version = "0.0.2"
edition = "2024"

[lib]
name = "ena_rs"
path = "src/lib.rs"

[[bin]]
name = "ena_rs"
path = "src/main.rs"

[dependencies]
tokio = {version = "1.49.0", features = ["full"]}
reqwest = {version = "0.12.28", features = ["json"]}
thiserror = {version = "2.0.17"}
serde = {version = "1.0.228", features = ["derive"]}
serde_json = {version = "1.0.149"}
clap = {version = "4.5.53", features = ["derive"]}
log = {version = "0.4.29", features =  ["serde"]}
simple_logger = {version = "5.1.0"}
url = {version = "2.5.8"}
md5 = {version = "0.8.0"}
struct-field-names-as-array = {version = "0.3.0"}
indicatif = {version = "0.18.3", features = ["tokio"]}
console = {version = "0.16.3"}
